version: "3.7"
services:
  clinic_bot:
    build: 
      context: ./bot
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: [ "python", "bot.py" ]
    env_file:
      - .env
    restart: always

  clinic_api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    expose:
      - "5555"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5555"]
    restart: always